[tool.poetry]
name = "bayesian-deep-learning"
version = "0.1.0"
description = ""
authors = ["Jochem Gietema <jochem@giete.ma>"]
packages = [ {include = "bdl"} ]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
matplotlib = "*"
pandas = "*"
scikit-learn = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
black = {version = "*", allow-prereleases = true}
isort = "*"
flake8 = "*"
taskipy = "*"

[tool.poetry.group.tensorflow]
optional = true

[tool.poetry.group.tensorflow.dependencies]
tensorflow = "2.9.0"

[tool.poetry.group.tensorflow-m1]
optional = true

[tool.poetry.group.tensorflow-m1.dependencies]
tensorflow-macos = "2.9.0"
tensorflow-metal = "0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "poetry run pytest"
lint = "poetry run black . && poetry run isort . && poetry run flake8 tests"

[tool.black]
line-length = 88
include = "\\.pyi?$"
exclude = """
/(
    \\.git
  | \\.tox
  | \\.venv
  | notebooks
  | reports
)/
"""
